// <auto-generated: QwenCoder>
// Fase: FASE-03 - Integração Monaco Editor (highlights de erros, quick fixes)
// Propósito: Hook React para gerenciar estado de highlights e quick fixes
// Dependências: React, error-highlights.ts

import { useState, useCallback, useEffect } from 'react'
import type { IErrorHighlight, IQuickFixAction } from '../opide/monaco-highlights/error-highlights'

export interface UseErrorHighlightsState {
  errors: IErrorHighlight[]
  quickFixes: IQuickFixAction[]
  isLoading: boolean
  error: string | null
}

export interface UseErrorHighlightsActions {
  addError: (error: IErrorHighlight) => void
  removeError: (index: number) => void
  clearErrors: () => void
  applyQuickFix: (action: IQuickFixAction) => Promise<boolean>
  refreshQuickFixes: (line: number, column: number) => void
}

/**
 * FASE-03: Hook para gerenciar highlights de erros no editor
 * Fornece estado reativo e ações para mostrar/esconder erros e aplicar quick fixes
 */
export function useErrorHighlights(
  uri: string,
  autoRefresh: boolean = true
): UseErrorHighlightsState & UseErrorHighlightsActions {
  const [errors, setErrors] = useState<IErrorHighlight[]>([])
  const [quickFixes, setQuickFixes] = useState<IQuickFixAction[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Carrega ErrorHighlightManager dinamicamente
  const [manager, setManager] = useState<any>(null)

  useEffect(() => {
    let mounted = true

    async function loadManager() {
      try {
        setIsLoading(true)
        const { ErrorHighlightManager } = await import('../opide/monaco-highlights/error-highlights')
        if (mounted) {
          setManager(ErrorHighlightManager.getInstance())
        }
      } catch (err) {
        console.error('[FASE-03] Failed to load ErrorHighlightManager:', err)
        if (mounted) {
          setError('Falha ao carregar sistema de erros')
        }
      } finally {
        if (mounted) {
          setIsLoading(false)
        }
      }
    }

    loadManager()

    return () => {
      mounted = false
    }
  }, [])

  /**
   * Adiciona um erro aos highlights
   */
  const addError = useCallback((newError: IErrorHighlight) => {
    setErrors(prev => {
      const updated = [...prev, newError]
      
      // Atualiza manager se disponível
      if (manager && uri) {
        manager.addHighlights(uri, updated)
      }
      
      return updated
    })
  }, [manager, uri])

  /**
   * Remove um erro pelo índice
   */
  const removeError = useCallback((index: number) => {
    setErrors(prev => {
      const updated = prev.filter((_, i) => i !== index)
      
      // Re-aplica highlights atualizados
      if (manager && uri) {
        manager.addHighlights(uri, updated)
      }
      
      return updated
    })
  }, [manager, uri])

  /**
   * Limpa todos os erros
   */
  const clearErrors = useCallback(() => {
    setErrors([])
    setQuickFixes([])
    
    if (manager && uri) {
      manager.removeHighlights(uri)
    }
    
    console.log('[FASE-03] Cleared all errors via hook')
  }, [manager, uri])

  /**
   * Aplica um quick fix
   */
  const applyQuickFix = useCallback(async (action: IQuickFixAction): Promise<boolean> => {
    if (!manager) {
      setError('Manager não carregado')
      return false
    }

    try {
      setIsLoading(true)
      const success = await manager.applyQuickFix(action)
      
      if (success) {
        // Remove o erro associado após aplicar o fix
        setErrors(prev => prev.filter(e => 
          !e.actions?.some(a => a.id === action.id)
        ))
        setQuickFixes(prev => prev.filter(a => a.id !== action.id))
      }
      
      return success
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : 'Falha ao aplicar quick fix'
      setError(errorMsg)
      return false
    } finally {
      setIsLoading(false)
    }
  }, [manager])

  /**
   * Atualiza quick fixes disponíveis para uma posição
   */
  const refreshQuickFixes = useCallback((line: number, column: number) => {
    if (!manager || !uri) return

    try {
      const fixes = manager.getQuickFixesAtPosition(uri, line, column)
      setQuickFixes(fixes)
      console.log(`[FASE-03] Found ${fixes.length} quick fixes at ${line}:${column}`)
    } catch (err) {
      console.warn('[FASE-03] Failed to get quick fixes:', err)
    }
  }, [manager, uri])

  // Auto-refresh quando URI muda
  useEffect(() => {
    if (autoRefresh && manager && uri) {
      refreshQuickFixes(1, 1)
    }
  }, [uri, autoRefresh, manager, refreshQuickFixes])

  return {
    // State
    errors,
    quickFixes,
    isLoading,
    error,
    // Actions
    addError,
    removeError,
    clearErrors,
    applyQuickFix,
    refreshQuickFixes,
  }
}

export default useErrorHighlights
