// <auto-generated: QwenCoder>
// Fase: FASE-04
// Propósito: Wizard de onboarding interativo para primeira execução do modo EDU
// Dependências: React, Tauri API

import { useState, useEffect } from 'react';
import { invoke } from '@tauri-apps/api/core';
import './EduWizard.css';

interface WizardStep {
  id: number;
  title: string;
  description: string;
  icon: string;
  action?: () => void;
}

interface EduWizardProps {
  onComplete: () => void;
  onSkip: () => void;
}

const steps: WizardStep[] = [
  {
    id: 1,
    title: 'Bem-vindo ao OPIDE Edu!',
    description: 'Este é um ambiente de programação simplificado para aprendizado. Vamos configurar sua experiência?',
    icon: '🎓',
  },
  {
    id: 2,
    title: 'Escolha seu Primeiro Projeto',
    description: 'Selecione um template para começar a codificar agora mesmo!',
    icon: '📁',
  },
  {
    id: 3,
    title: 'Dicas Rápidas',
    description: 'Use o botão ▶️ para rodar seu código e 🤖 para pedir explicações à IA.',
    icon: '💡',
  },
  {
    id: 4,
    title: 'Tudo Pronto!',
    description: 'Você está pronto para começar. Boa jornada de aprendizado!',
    icon: '🚀',
  },
];

export function EduWizard({ onComplete, onSkip }: EduWizardProps) {
  const [currentStep, setCurrentStep] = useState(0);
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
  const [isCompleting, setIsCompleting] = useState(false);

  const templates = [
    {
      id: 'ola-mundo',
      name: 'Olá Mundo',
      language: 'python',
      description: 'Seu primeiro programa em Python',
      icon: '🐍',
    },
    {
      id: 'calculadora',
      name: 'Calculadora',
      language: 'javascript',
      description: 'Uma calculadora interativa',
      icon: '🧮',
    },
    {
      id: 'turtle',
      name: 'Turtle Graphics',
      language: 'python',
      description: 'Desenhe com código!',
      icon: '🐢',
    },
  ];

  useEffect(() => {
    // Marcar wizard como completo no backend
    invoke('mark_onboarding_complete')
      .catch(() => {
        // Ignora erro se comando não existir ainda
      });
  }, []);

  const handleNext = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep(currentStep + 1);
    } else {
      handleComplete();
    }
  };

  const handleBack = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleSelectTemplate = (templateId: string) => {
    setSelectedTemplate(templateId);
  };

  const handleComplete = async () => {
    setIsCompleting(true);
    
    if (selectedTemplate) {
      try {
        await invoke('create_edu_project', { 
          templateId: selectedTemplate,
          projectName: 'meu-primeiro-projeto'
        });
      } catch (error) {
        console.error('Erro ao criar projeto:', error);
      }
    }

    onComplete();
  };

  const renderStep1 = () => (
    <div className="wizard-step welcome">
      <div className="wizard-icon">{steps[0].icon}</div>
      <h2>{steps[0].title}</h2>
      <p>{steps[0].description}</p>
      <div className="welcome-features">
        <div className="feature">
          <span className="feature-icon">🎯</span>
          <span>Foco no aprendizado</span>
        </div>
        <div className="feature">
          <span className="feature-icon">🤖</span>
          <span>IA para te ajudar</span>
        </div>
        <div className="feature">
          <span className="feature-icon">⚡</span>
          <span>Execução rápida</span>
        </div>
      </div>
    </div>
  );

  const renderStep2 = () => (
    <div className="wizard-step templates">
      <div className="wizard-icon">{steps[1].icon}</div>
      <h2>{steps[1].title}</h2>
      <p>{steps[1].description}</p>
      <div className="template-grid">
        {templates.map((template) => (
          <button
            key={template.id}
            className={`template-card ${selectedTemplate === template.id ? 'selected' : ''}`}
            onClick={() => handleSelectTemplate(template.id)}
          >
            <span className="template-icon">{template.icon}</span>
            <h3>{template.name}</h3>
            <p>{template.description}</p>
            <span className="template-language">{template.language}</span>
          </button>
        ))}
      </div>
    </div>
  );

  const renderStep3 = () => (
    <div className="wizard-step tips">
      <div className="wizard-icon">{steps[2].icon}</div>
      <h2>{steps[2].title}</h2>
      <p>{steps[2].description}</p>
      <div className="tips-list">
        <div className="tip-item">
          <span className="tip-key">▶️ Rodar</span>
          <span>Execute seu código e veja o resultado</span>
        </div>
        <div className="tip-item">
          <span className="tip-key">🐛 Testar</span>
          <span>Verifique se seu código está correto</span>
        </div>
        <div className="tip-item">
          <span className="tip-key">🤖 Explicar</span>
          <span>Peça ajuda à IA quando tiver dúvidas</span>
        </div>
        <div className="tip-item">
          <span className="tip-key">💾 Salvar</span>
          <span>Guarde seu progresso automaticamente</span>
        </div>
      </div>
    </div>
  );

  const renderStep4 = () => (
    <div className="wizard-step complete">
      <div className="wizard-icon">{steps[3].icon}</div>
      <h2>{steps[3].title}</h2>
      <p>{steps[3].description}</p>
      {selectedTemplate && (
        <div className="selected-project">
          <p>Projeto selecionado: <strong>{templates.find(t => t.id === selectedTemplate)?.name}</strong></p>
        </div>
      )}
      {!selectedTemplate && (
        <p className="no-project">Você pode criar um projeto depois nas configurações.</p>
      )}
    </div>
  );

  const renderContent = () => {
    switch (currentStep) {
      case 0: return renderStep1();
      case 1: return renderStep2();
      case 2: return renderStep3();
      case 3: return renderStep4();
      default: return renderStep1();
    }
  };

  return (
    <div className="edu-wizard-overlay">
      <div className="edu-wizard">
        <div className="wizard-header">
          <div className="wizard-progress">
            {steps.map((step, index) => (
              <div
                key={step.id}
                className={`progress-dot ${index <= currentStep ? 'active' : ''}`}
              />
            ))}
          </div>
          <button className="wizard-skip" onClick={onSkip}>
            Pular
          </button>
        </div>

        <div className="wizard-content">
          {renderContent()}
        </div>

        <div className="wizard-footer">
          <button
            className="wizard-btn back"
            onClick={handleBack}
            disabled={currentStep === 0}
          >
            ← Voltar
          </button>
          
          <button
            className="wizard-btn next"
            onClick={handleNext}
            disabled={isCompleting}
          >
            {currentStep === steps.length - 1 ? 'Começar!' : 'Próximo →'}
          </button>
        </div>
      </div>
    </div>
  );
}
