/**
 * <auto-generated: QwenCoder>
 * Fase: FASE-01 - UI Simplification (Edu Mode)
 * Propósito: Barra de ações flutuante para modo educacional
 * Ações: ▶️ Rodar, 🐛 Testar, 🤖 Explicar, 💾 Salvar
 * Dependências: Tauri IPC
 */

import { invoke } from '@tauri-apps/api/core'
import { addXp, getPlayerStats, unlockAchievement } from '../services/edu-progress'

interface EduActionBarProps {
  onActionClick?: (action: string) => void
}

export function EduActionBar({ onActionClick }: EduActionBarProps) {
  const actions = [
    { id: 'run', label: 'Rodar', icon: '▶️', color: '#4CAF50' },
    { id: 'test', label: 'Testar', icon: '🐛', color: '#FF9800' },
    { id: 'explain', label: 'Explicar', icon: '🤖', color: '#2196F3' },
    { id: 'templates', label: 'Templates', icon: '📂', color: '#E8B931' },
    { id: 'leaderboard', label: 'Ranking', icon: '🏆', color: '#FFD700' },
    { id: 'lms', label: 'LMS', icon: '📤', color: '#81c784' },
    { id: 'save', label: 'Salvar', icon: '💾', color: '#9C27B0' },
  ]

  async function handleAction(actionId: string) {
    try {
      onActionClick?.(actionId)

      const currentStats = await getPlayerStats();

      switch (actionId) {
        case 'run':
          await invoke('edu_run_code')
          await addXp(10)
          if (!currentStats.achievements.includes('first_run')) {
            await unlockAchievement('first_run')
          }
          break
        case 'test':
          await invoke('edu_test_code')
          await addXp(15)
          if (!currentStats.achievements.includes('first_test')) {
            await unlockAchievement('first_test')
          }
          break
        case 'explain':
          await invoke('edu_explain_code')
          await addXp(20)
          if (!currentStats.achievements.includes('explain_used')) {
            await unlockAchievement('explain_used')
          }
          break
        case 'save':
          await invoke('edu_save_file')
          break
        case 'templates':
        case 'leaderboard':
        case 'lms':
          // Handle in parent orchestrator
          break
        default:
          console.warn(`[EduActionBar] Unknown action: ${actionId}`)
      }
    } catch (error) {
      console.error(`[EduActionBar] Action ${actionId} failed:`, error)
    }
  }

  return (
    <div className="edu-action-bar">
      {actions.map((action) => (
        <button
          key={action.id}
          className={`edu-action-btn edu-action-${action.id}`}
          onClick={() => handleAction(action.id)}
          title={action.label}
          style={{ '--action-color': action.color } as React.CSSProperties}
        >
          <span className="action-icon">{action.icon}</span>
          <span className="action-label">{action.label}</span>
        </button>
      ))}
    </div>
  )
}
