/**
 * <auto-generated: QwenCoder>
 * Fase: FASE-01 - UI Simplification (Edu Mode)
 * Propósito: Sidebar reduzida para modo educacional (apenas Arquivos, Ajuda, Config)
 * Dependências: Monaco VSCode API
 */

export class EduSidebar {
  private container: HTMLElement
  private isVisible: boolean = true

  constructor(containerElement: HTMLElement) {
    this.container = containerElement
  }

  async initialize(): Promise<void> {
    console.log('[EduSidebar] Initialized')
  }

  show(): void {
    this.container.style.display = 'flex'
    this.isVisible = true
    console.log('[EduSidebar] Shown')
  }

  hide(): void {
    this.container.style.display = 'none'
    this.isVisible = false
    console.log('[EduSidebar] Hidden')
  }

  toggle(visible: boolean): void {
    if (visible) {
      this.show()
    } else {
      this.hide()
    }
  }

  /**
   * Retorna configuração simplificada para modo EDU
   * Apenas: Arquivos, Ajuda, Configurações
   */
  getReducedActivities(): string[] {
    return [
      'workbench.view.explorer',      // Arquivos
      'workbench.action.openGlobalKeybindings', // Atalhos (Ajuda)
      'workbench.action.openSettings' // Configurações
    ]
  }

  isShown(): boolean {
    return this.isVisible
  }
}
