/**
 * <auto-generated: QwenCoder>
 * Fase: FASE-01 - UI Simplification (Edu Mode)
 * Propósito: Sidebar reduzida para modo educacional (apenas Arquivos, Ajuda, Config)
 * Dependências: Monaco VSCode API
 */

import { getActiveService } from '@codingame/monaco-vscode-api'
import type { IExplorerService } from '@codingame/monaco-vscode-explorer-service-override'

interface EduSidebarProps {
  containerElement: HTMLElement
}

export class EduSidebar {
  private container: HTMLElement
  private explorerService: IExplorerService | null = null
  private isVisible: boolean = true

  constructor(containerElement: HTMLElement) {
    this.container = containerElement
  }

  async initialize(): Promise<void> {
    try {
      // Tentar obter o serviço de explorer
      this.explorerService = await getActiveService<IExplorerService>('explorerService')
      console.log('[EduSidebar] Explorer service initialized')
    } catch (error) {
      console.warn('[EduSidebar] Explorer service not available:', error)
    }
  }

  show(): void {
    this.container.style.display = 'flex'
    this.isVisible = true
    console.log('[EduSidebar] Shown')
  }

  hide(): void {
    this.container.style.display = 'none'
    this.isVisible = false
    console.log('[EduSidebar] Hidden')
  }

  toggle(visible: boolean): void {
    if (visible) {
      this.show()
    } else {
      this.hide()
    }
  }

  /**
   * Retorna configuração simplificada para modo EDU
   * Apenas: Arquivos, Ajuda, Configurações
   */
  getReducedActivities(): string[] {
    return [
      'workbench.view.explorer',      // Arquivos
      'workbench.action.openGlobalKeybindings', // Atalhos (Ajuda)
      'workbench.action.openSettings' // Configurações
    ]
  }

  isShown(): boolean {
    return this.isVisible
  }
}
