/**
 * <auto-generated: QwenCoder>
 * Fase: FASE-01 - UI Simplification (Edu Mode)
 * Propósito: Componente de toggle para alternar entre modos EDU e PRO
 * Dependências: Nenhuma
 */

import { useState, useEffect } from 'react'
import { invoke } from '@tauri-apps/api/core'

interface EduToggleProps {
  onModeChange?: (isEdu: boolean) => void
}

export function EduToggle({ onModeChange }: EduToggleProps) {
  const [isEduMode, setIsEduMode] = useState<boolean>(false)
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    // Carregar estado atual do modo EDU/PRO
    loadEduMode()
  }, [])

  async function loadEduMode() {
    try {
      const isEdu = await invoke<boolean>('get_edu_mode')
      setIsEduMode(isEdu)
      onModeChange?.(isEdu)
    } catch (error) {
      console.error('Failed to load edu mode:', error)
      // Default para false (PRO) se falhar
      setIsEduMode(false)
    } finally {
      setLoading(false)
    }
  }

  async function toggleEduMode() {
    try {
      const newMode = !isEduMode
      await invoke('toggle_edu_mode', { enabled: newMode })
      setIsEduMode(newMode)
      onModeChange?.(newMode)
      
      // Aplicar tema ao documento
      document.documentElement.setAttribute('data-edu-mode', String(newMode))
      
      // Recarregar workbench para aplicar mudanças
      if (confirm(`Mudar para modo ${newMode ? 'Educacional' : 'Profissional'}? A aplicação será recarregada.`)) {
        window.location.reload()
      }
    } catch (error) {
      console.error('Failed to toggle edu mode:', error)
      alert('Erro ao alternar modo. Tente novamente.')
    }
  }

  if (loading) {
    return (
      <div className="edu-toggle loading">
        <span>Carregando...</span>
      </div>
    )
  }

  return (
    <div className="edu-toggle">
      <button
        onClick={toggleEduMode}
        className={`edu-toggle-btn ${isEduMode ? 'edu-active' : 'pro-active'}`}
        title={isEduMode ? 'Modo Educacional ativo - Clique para mudar para PRO' : 'Modo Profissional ativo - Clique para mudar para EDU'}
      >
        <span className="toggle-icon">{isEduMode ? '🎓' : '💼'}</span>
        <span className="toggle-label">{isEduMode ? 'Modo Aula' : 'Modo PRO'}</span>
      </button>
    </div>
  )
}
