/**
 * <auto-generated: QwenCoder>
 * Fase: FASE-01 - UI Simplification (Edu Mode)
 * Propósito: Componente de toggle para alternar entre modos EDU e PRO
 * Dependências: Nenhuma
 */

import { useState, useEffect } from 'react'
import { invoke } from '@tauri-apps/api/core'

interface EduToggleProps {
  onModeChange?: (isEdu: boolean) => void
}

export function isEduMode(): boolean {
  return localStorage.getItem('opide:edu-mode') === 'true'
}

export function EduToggle({ onModeChange }: EduToggleProps) {
  const [isEduModeState, setIsEduMode] = useState<boolean>(false)
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    // Carregar estado atual do modo EDU/PRO
    loadEduMode()
  }, [])

  async function loadEduMode() {
    try {
      const isEdu = await invoke<boolean>('get_edu_mode')
      setIsEduMode(isEdu)
      localStorage.setItem('opide:edu-mode', String(isEdu))
      document.documentElement.setAttribute('data-edu-mode', String(isEdu))
      onModeChange?.(isEdu)
    } catch (error) {
      console.error('Failed to load edu mode:', error)
      // Fallback para localStorage
      const isEduLocal = isEduMode()
      setIsEduMode(isEduLocal)
      onModeChange?.(isEduLocal)
    } finally {
      setLoading(false)
    }
  }

  async function toggleEduMode() {
    try {
      const newMode = !isEduModeState
      await invoke('toggle_edu_mode', { enabled: newMode })
      setIsEduMode(newMode)
      localStorage.setItem('opide:edu-mode', String(newMode))
      onModeChange?.(newMode)
      
      // Aplicar tema ao documento
      document.documentElement.setAttribute('data-edu-mode', String(newMode))
      
      // Recarregar workbench para aplicar mudanças
      if (confirm(`Mudar para modo ${newMode ? 'Educacional' : 'Profissional'}? A aplicação será recarregada.`)) {
        window.location.reload()
      }
    } catch (error) {
      console.error('Failed to toggle edu mode:', error)
      alert('Erro ao alternar modo. Tente novamente.')
    }
  }

  if (loading) {
    return (
      <div className="edu-toggle loading">
        <span>Carregando...</span>
      </div>
    )
  }

  return (
    <div className="edu-toggle">
      <button
        onClick={toggleEduMode}
        className={`edu-toggle-btn ${isEduModeState ? 'edu-active' : 'pro-active'}`}
        title={isEduModeState ? 'Modo Educacional ativo - Clique para mudar para PRO' : 'Modo Profissional ativo - Clique para mudar para EDU'}
      >
        <span className="toggle-icon">{isEduModeState ? '🎓' : '💼'}</span>
        <span className="toggle-label">{isEduModeState ? 'Modo Aula' : 'Modo PRO'}</span>
      </button>
    </div>
  )
}
