// <auto-generated: QwenCoder>
// Fase: FASE-03 - Integração Monaco Editor (highlights de erros, quick fixes)
// Propósito: Sistema de highlights de erros e quick fixes no Monaco Editor
// Dependências: @codingame/monaco-vscode-api, markers-service-override

import { editor, MarkerSeverity, Range, Uri, languages } from 'monaco-editor'

export interface IErrorHighlight {
  severity: MarkerSeverity
  message: string
  startLineNumber: number
  startColumn: number
  endLineNumber: number
  endColumn: number
  code?: string
  source?: string
  relatedInformation?: editor.IMarkerData[]
  actions?: IQuickFixAction[]
}

export interface IQuickFixAction {
  id: string
  title: string
  kind?: string
  isPreferred?: boolean
  disabled?: boolean
  tooltip?: string
  command?: {
    id: string
    title: string
    arguments?: any[]
  }
  edit?: {
    edits: ITextEdit[]
  }
}

export interface ITextEdit {
  resource: string
  edit: {
    range: {
      startLineNumber: number
      startColumn: number
      endLineNumber: number
      endColumn: number
    }
    text: string
  }
}

/**
 * FASE-03: Gerenciador de highlights de erros no editor
 * Integra-se com o Monaco Marker Service para mostrar erros de forma não intrusiva
 */
export class ErrorHighlightManager {
  private static instance: ErrorHighlightManager | null = null
  private markerCollection: Map<string, editor.IMarkerData[]> = new Map()
  private quickFixes: Map<string, IQuickFixAction[]> = new Map()
  private decorationCollection: Map<string, editor.IEditorDecorationsCollection> = new Map()
  private editorInstance: editor.IStandaloneCodeEditor | null = null

  private constructor() {}

  public static getInstance(): ErrorHighlightManager {
    if (!ErrorHighlightManager.instance) {
      ErrorHighlightManager.instance = new ErrorHighlightManager()
    }
    return ErrorHighlightManager.instance
  }

  /**
   * Registra um editor para gerenciar highlights
   */
  public registerEditor(editorInstance: editor.IStandaloneCodeEditor): void {
    this.editorInstance = editorInstance
    const model = editorInstance.getModel()
    if (model) {
      const uri = model.uri.toString()
      if (!this.decorationCollection.has(uri)) {
        const collection = editorInstance.createDecorationsCollection()
        this.decorationCollection.set(uri, collection)
      }
    }
  }

  /**
   * Adiciona highlights de erro para um arquivo
   */
  public addHighlights(uri: string, errors: IErrorHighlight[]): void {
    const markers: editor.IMarkerData[] = errors.map(err => ({
      severity: err.severity,
      message: err.message,
      startLineNumber: err.startLineNumber,
      startColumn: err.startColumn,
      endLineNumber: err.endLineNumber,
      endColumn: err.endColumn,
      code: err.code ? { value: err.code, target: undefined } : undefined,
      source: err.source,
      relatedInformation: err.relatedInformation,
    }))

    // Atualiza markers no Monaco
    const modelUri = Uri.parse(uri)
    editor.setModelMarkers(
      editor.getModel(modelUri) || { uri: modelUri } as any,
      'opide-errors',
      markers
    )

    this.markerCollection.set(uri, markers)

    // Armazena quick fixes associados
    const actions: IQuickFixAction[] = []
    errors.forEach(err => {
      if (err.actions) {
        actions.push(...err.actions)
      }
    })
    this.quickFixes.set(uri, actions)

    // Atualiza decorações visuais
    this.updateDecorations(uri, errors)

    console.log(`[FASE-03] Added ${errors.length} error highlights to ${uri}`)
  }

  /**
   * Remove highlights de um arquivo
   */
  public removeHighlights(uri: string): void {
    const modelUri = Uri.parse(uri)
    editor.setModelMarkers(
      editor.getModel(modelUri) || { uri: modelUri } as any,
      'opide-errors',
      []
    )

    this.markerCollection.delete(uri)
    this.quickFixes.delete(uri)

    if (this.decorationCollection.has(uri)) {
      this.decorationCollection.get(uri)!.clear()
      this.decorationCollection.delete(uri)
    }

    console.log(`[FASE-03] Removed error highlights from ${uri}`)
  }

  /**
   * Limpa todos os highlights
   */
  public clearAll(): void {
    this.markerCollection.forEach((_, uri) => this.removeHighlights(uri))
    console.log('[FASE-03] Cleared all error highlights')
  }

  /**
   * Obtém quick fixes disponíveis para uma posição
   */
  public getQuickFixesAtPosition(uri: string, lineNumber: number, column: number): IQuickFixAction[] {
    const markers = this.markerCollection.get(uri) || []
    const relevantErrors = markers.filter(m => 
      lineNumber >= m.startLineNumber && 
      lineNumber <= m.endLineNumber &&
      column >= m.startColumn && 
      column <= m.endColumn
    )

    const actions: IQuickFixAction[] = []
    relevantErrors.forEach(marker => {
      const markerKey = `${uri}:${marker.startLineNumber}:${marker.startColumn}`
      const storedActions = this.quickFixes.get(markerKey) || []
      actions.push(...storedActions)
    })

    return actions
  }

  /**
   * Aplica um quick fix
   */
  public async applyQuickFix(action: IQuickFixAction): Promise<boolean> {
    if (!action.edit || !action.edit.edits) {
      console.warn('[FASE-03] Quick fix has no edits')
      return false
    }

    try {
      const workspaceEdit = new languages.WorkspaceEdit()
      
      for (const textEdit of action.edit.edits) {
        const uri = Uri.parse(textEdit.resource)
        const range = new Range(
          textEdit.edit.range.startLineNumber,
          textEdit.edit.range.startColumn,
          textEdit.edit.range.endLineNumber,
          textEdit.edit.range.endColumn
        )
        
        if (!workspaceEdit.edits) {
          workspaceEdit.edits = []
        }
        workspaceEdit.edits.push({
          resource: uri,
          edit: {
            range,
            text: textEdit.edit.text
          }
        })
      }

      // Aplica a edição
      await languages.applyWorkspaceEdit(workspaceEdit)
      console.log(`[FASE-03] Applied quick fix: ${action.title}`)
      return true
    } catch (error) {
      console.error('[FASE-03] Failed to apply quick fix:', error)
      return false
    }
  }

  /**
   * Atualiza decorações visuais para erros
   */
  private updateDecorations(uri: string, errors: IErrorHighlight[]): void {
    if (!this.editorInstance) return

    const model = this.editorInstance.getModel()
    if (!model || model.uri.toString() !== uri) return

    const decorations = errors.map(err => ({
      range: new Range(
        err.startLineNumber,
        err.startColumn,
        err.endLineNumber,
        err.endColumn
      ),
      options: {
        isWholeLine: false,
        glyphMarginClassName: err.severity === MarkerSeverity.Error 
          ? 'codicon codicon-error' 
          : err.severity === MarkerSeverity.Warning 
            ? 'codicon codicon-warning' 
            : 'codicon codicon-info',
        glyphMarginHoverMessage: { value: err.message },
        className: err.severity === MarkerSeverity.Error 
          ? 'opide-error-line' 
          : err.severity === MarkerSeverity.Warning 
            ? 'opide-warning-line' 
            : 'opide-info-line',
        hoverMessage: { value: err.message },
        minimap: {
          color: err.severity === MarkerSeverity.Error 
            ? '#ff6b6b' 
            : err.severity === MarkerSeverity.Warning 
              ? '#ffd93d' 
              : '#6bcb77',
          position: 1
        }
      }
    }))

    const collection = this.decorationCollection.get(uri)
    if (collection) {
      collection.set(decorations)
    }
  }
}

/**
 * FASE-03: Factory para criar erros comuns de compilação
 */
export class ErrorHighlightFactory {
  /**
   * Cria highlight para erro de sintaxe
   */
  public static createSyntaxError(
    line: number,
    column: number,
    endLine: number,
    endColumn: number,
    message: string,
    suggestion?: string
  ): IErrorHighlight {
    const actions: IQuickFixAction[] = []
    
    if (suggestion) {
      actions.push({
        id: 'fix-syntax',
        title: `Corrigir: ${suggestion}`,
        kind: 'quickfix',
        isPreferred: true,
        edit: {
          edits: [{
            resource: '',
            edit: {
              range: {
                startLineNumber: line,
                startColumn: column,
                endLineNumber: endLine,
                endColumn: endColumn
              },
              text: suggestion
            }
          }]
        }
      })
    }

    return {
      severity: MarkerSeverity.Error,
      message,
      startLineNumber: line,
      startColumn: column,
      endLineNumber: endLine,
      endColumn: endColumn,
      code: 'syntax-error',
      source: 'OPIDE',
      actions
    }
  }

  /**
   * Cria highlight para erro de tipo
   */
  public static createTypeError(
    line: number,
    column: number,
    message: string,
    expectedType: string,
    actualType: string
  ): IErrorHighlight {
    return {
      severity: MarkerSeverity.Error,
      message: `${message}: esperado ${expectedType}, recebido ${actualType}`,
      startLineNumber: line,
      startColumn: column,
      endLineNumber: line,
      endColumn: column + 10,
      code: 'type-error',
      source: 'OPIDE Type Checker',
      actions: [{
        id: 'fix-type',
        title: `Converter para ${expectedType}`,
        kind: 'quickfix',
        edit: {
          edits: [{
            resource: '',
            edit: {
              range: {
                startLineNumber: line,
                startColumn: column,
                endLineNumber: line,
                endColumn: column + 10
              },
              text: `(${expectedType})`
            }
          }]
        }
      }]
    }
  }

  /**
   * Cria highlight para warning
   */
  public static createWarning(
    line: number,
    column: number,
    message: string,
    suggestion?: string
  ): IErrorHighlight {
    const actions: IQuickFixAction[] = []
    
    if (suggestion) {
      actions.push({
        id: 'fix-warning',
        title: `Aplicar sugestão: ${suggestion}`,
        kind: 'quickfix',
        isPreferred: false,
        edit: {
          edits: [{
            resource: '',
            edit: {
              range: {
                startLineNumber: line,
                startColumn: column,
                endLineNumber: line,
                endColumn: column + 20
              },
              text: suggestion
            }
          }]
        }
      })
    }

    return {
      severity: MarkerSeverity.Warning,
      message,
      startLineNumber: line,
      startColumn: column,
      endLineNumber: line,
      endColumn: column + 20,
      code: 'warning',
      source: 'OPIDE Linter',
      actions
    }
  }
}

export default ErrorHighlightManager
