// <auto-generated: QwenCoder>
// Fase: FASE-03 - Integração Monaco Editor (highlights de erros, quick fixes)
// Propósito: Barrel exports para o módulo monaco-highlights
// Dependências: error-highlights.ts

export { 
  ErrorHighlightManager, 
  ErrorHighlightFactory 
} from './error-highlights'

export type {
  IErrorHighlight,
  IQuickFixAction,
  ITextEdit
} from './error-highlights'

export { useErrorHighlights } from '../../hooks/useErrorHighlights'
export type {
  UseErrorHighlightsState,
  UseErrorHighlightsActions
} from '../../hooks/useErrorHighlights'
